# CPU pilot — small model, small user subset (NOT a main-table result)

Auto-generated by `scripts/pilot_report.py`; do not hand-edit. This pilot only shows that the offline pipeline (profile → teacher ranking → PCS verification → distillation → online export → evaluation) runs end to end with a real LLM. The teacher is **Qwen2.5-1.5B-Instruct on CPU**, not the paper's Qwen2.5-7B-Instruct, and only **60 users** get LLM signals; the student metrics below are therefore not evidence for or against the method.

## 1. LLM stage (measured)

- model `Qwen/Qwen2.5-1.5B-Instruct`, backend `transformers`, dtype bfloat16, 2 CPU threads, batch 4 (greedy); box shared with 2 training jobs × 3 threads.
- users: 60; total generation wall time 66.9 min → **66.9 s/user**; aggregate decode 8.5 completion tok/s.

| call type | #calls | prompt tok/call | completion tok/call | s/call (amortised over batch) | JSON parse ok |
|---|---|---|---|---|---|
| profile | 60 | 622 | 181 | 22.4 | 1.00 |
| rank+reasons | 60 | 1149 | 137 | 14.9 | 1.00 |
| rank | 120 | 1102 | 125 | 14.8 | 0.95 |

## 2. PCS verification (measured, no LLM judge)

| quantity | value |
|---|---|
| n_users | 60 |
| claims_per_user | 3.8167 |
| G | 0.0908 |
| halluc_evidence_rate | 0.0000 |
| grounded_claim_rate | 0.0394 |
| T_auc | 0.6081 |
| R | 0.5449 |
| kendall_tau | 0.0897 |
| position_bias_tau | 0.5871 |
| F | 0.1028 |
| PCS | 0.0286 |
| w | 0.0578 |
| users_hard_filtered(w=0) | 34 |
| teacher_gt_rank_mean(0=top) | 9.9667 |
| teacher_gt_top1_rate | 0.0333 |
| teacher_gt_top5_rate | 0.2500 |
| align_eligible_users | 26 |
| profile_parse_rate | 1.0000 |
| profile_salvaged_rate | 0.5667 |
| rank_parse_rate | 1.0000 |
| rank_missing_appended_mean | 7.7111 |
| elapsed_sec | 32.5820 |

NLI model `cross-encoder/nli-deberta-v3-xsmall`, sentence encoder `sentence-transformers/all-MiniLM-L6-v2`; candidates M = 20 from Stage-0 SASRec (seed 42), so a random teacher puts the target in the top-5 with p = 0.25 and a mean GT rank of 9.5 (0 = top). Measured here: top-5 rate 0.25, mean rank 9.97.

## 3. Student distillation (all 22,363 users evaluated; LLM signals only for the pilot users)

| run | valid NDCG@10 | test NDCG@10 | test HR@10 | teacher users: test NDCG@10 (n) | best epoch | minutes |
|---|---|---|---|---|---|---|
| SASRec seed 42 (Stage-0 / reference) | 0.0517 | 0.0405 | 0.0762 | - | - | - |
| pcdrec_pilot_s42 | 0.0517 | 0.0405 | 0.0762 | 0.0618 (60) | 0 | 1.9 |
| pilot_a1_naive_s42 | 0.0517 | 0.0405 | 0.0762 | 0.0618 (60) | 0 | 1.9 |

- `pcdrec_pilot_s42`: no epoch improved valid NDCG@10 over the Stage-0 initialisation (epochs run: 3), so the selected checkpoint **is** Stage-0 and its test metrics equal Stage-0. This pilot shows no effect either way.
- `pilot_a1_naive_s42`: no epoch improved valid NDCG@10 over the Stage-0 initialisation (epochs run: 3), so the selected checkpoint **is** Stage-0 and its test metrics equal Stage-0. This pilot shows no effect either way.

## 4. Online export (measured)

- export_dir: results/pilot/online_export
- online_llm_calls: 0
- state_dict_keys: 36
- n_params: 877824
- dropped_training_only_modules: ['g', 'pool']
- llm_modules_imported_during_check: []
- export_test_ndcg@10: 0.04052820891929213
- export_test_hr@10: 0.07619729016679336
- latency_ms_batch1_1thread_p50: 0.9053409958141856
- latency_ms_batch1_1thread_p95: 1.072560841566883
- latency_n_requests: 2000
- student_test_ndcg@10: 0.04052820891929213
- export_matches_student: True

## 5. Cost estimate for all 22,363 users

Notation per user: c = calls, p = prompt tokens, o = completion tokens (pilot means). N = 22,363.

- CPU, 1.5B, pilot config (measured): T = N · s_user, with s_user the measured generation seconds per user.
- CPU, 1.5B, full-plan rows: T = N · o_user / r_dec, with r_dec the measured aggregate completion tok/s.
- CPU, 7B (**scaled, assumed**): T_7B = T_1.5B · 7.61 / 1.54. This is not feasible on this box: bf16 weights need ~15 GB of the ~15 GB RAM, so a 4-/8-bit build or a larger machine would be needed.
- 7B on one 24 GB GPU (**assumed**): T = N · (o_user / R_dec + p_user / R_prefill).
- API (**assumed price**): cost = N · (p_user · $in + o_user · $out) / 10⁶.
- Full-plan config (`configs/llm/qwen2.5-7b.yaml`): reasons for all 20 candidates in 3 of 3 permutations. `full_plan_extrapolated` takes o_rank + 20 · o_reason, with o_reason = 4.0 tok = (o_rank+reasons − o_rank) / 3 measured in the pilot. The 1.5B model often skips reasons, so this is likely an underestimate. `full_plan_token_budget` assumes every call uses its full max_tokens (3700 completion tok/user), which gives an upper bound.

| config | calls | prompt tok (M) | completion tok (M) | CPU 1.5B h (measured rate) | CPU 7B h (scaled) | 7B 24GB-GPU h, batched (assumed) | 7B GPU h, batch 1 (assumed) | 7B API USD (assumed price) |
|---|---|---|---|---|---|---|---|---|
| pilot_config | 89,452 | 88.9 | 12.7 | 416 | 2053 | 9.8 | 39.8 | 11.43 |
| full_plan_extrapolated | 89,452 | 91.0 | 17.8 | 583 | 2883 | 11.4 | 53.5 | 12.66 |
| full_plan_token_budget | 89,452 | 91.0 | 82.7 | 2707 | 13375 | 29.8 | 225.2 | 25.64 |

Assumptions (not measured on this box):

- `gpu_decode_tok_s_batched` = 980.0: Qwen2.5-7B-Instruct FP16, vLLM, single RTX 4090 24GB, aggregate decode tokens/s at batch 32 (prompt 512, gen 256). Source: https://gigagpu.com/rtx-4090-24gb-for-qwen-25-7b/ (third-party benchmark, vLLM 0.6.3, FP8 KV cache; accessed 2026-10-06)
- `gpu_decode_tok_s_batch1` = 105.0: Qwen2.5-7B-Instruct FP16, vLLM, single RTX 4090 24GB, batch-1 decode tokens/s (pessimistic: no batching). Source: https://gigagpu.com/rtx-4090-24gb-for-qwen-25-7b/ (accessed 2026-10-06); cross-check: the official Qwen2.5 speed benchmark reports 84.28 tok/s for 7B BF16 vLLM batch 1 on an A100 80GB (https://qwen.readthedocs.io/en/v2.5/benchmark/speed_benchmark.html)
- `gpu_prefill_tok_s` = 4000.0: Qwen2.5-7B prefill tokens/s on RTX 4090 (reported 3,800-4,200 t/s at 8k prompt for AWQ/FP8). Source: https://gigagpu.com/rtx-4090-24gb-for-qwen-25-7b/ (accessed 2026-10-06)
- `api_usd_per_M_input` = 0.1: qwen/qwen-2.5-7b-instruct list price on OpenRouter, input. Source: https://openrouter.ai/qwen/qwen-2.5-7b-instruct (list price as observed 2026-09/10; may change)
- `api_usd_per_M_output` = 0.2: qwen/qwen-2.5-7b-instruct list price on OpenRouter, output. Source: https://openrouter.ai/qwen/qwen-2.5-7b-instruct (list price as observed 2026-09/10; may change)
- `cpu_7b_over_1.5b_time_ratio` = 4.941558441558442: CPU decoding is memory-bandwidth bound, so 7B time ~ 1.5B time x parameter ratio (7.61B / 1.54B). Not measured: Qwen2.5-7B in bf16 needs ~15 GB for weights alone, more than this box's ~15 GB RAM. Source: parameter counts from the Qwen2.5-7B-Instruct / Qwen2.5-1.5B-Instruct model cards; linear scaling is an assumption
- `same_token_counts_for_7b` = True: prompt token counts transfer exactly (Qwen2.5 1.5B and 7B share one tokenizer); completion lengths of the 7B teacher are ASSUMED equal to the 1.5B pilot's. Source: Qwen2.5 model cards (shared tokenizer); completion-length equality is an assumption

PCS verification and distillation costs are not LLM costs. They are measured above: the verify elapsed_sec and the student minutes, on CPU.
