#!/usr/bin/env python
"""Aggregate SASRec full-data runs from results/*_metrics.json into a main table.

All numbers come from the JSON files written by `pcdrec.train`; nothing is hand-entered.

Usage:
  python scripts/06_tables.py                       # main table: all baselines -> results/main_table_beauty.{csv,md}
  python scripts/06_tables.py --glob 'results/sasrec_full_s*_metrics.json' --out-stem results/main_table_sasrec_full
"""

from __future__ import annotations

import argparse
import csv
import glob
import json
import math
import platform
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
METRICS = ["hr@5", "hr@10", "hr@20", "ndcg@5", "ndcg@10", "ndcg@20"]


def mean_std(xs: list[float]) -> tuple[float, float]:
    n = len(xs)
    m = sum(xs) / n
    # sample std (ddof=1); 0 for a single run
    s = math.sqrt(sum((x - m) ** 2 for x in xs) / (n - 1)) if n > 1 else 0.0
    return m, s


def main() -> None:
    import sys

    if "--glob" not in sys.argv:
        from main_table import main as main_table  # multi-method table + paired tests

        return main_table()
    ap = argparse.ArgumentParser()
    ap.add_argument("--glob", default=str(ROOT / "results" / "sasrec_full_s*_metrics.json"))
    ap.add_argument("--out-stem", default=str(ROOT / "results" / "main_table_sasrec_full"))
    ap.add_argument("--expect-users", type=int, default=22363)
    args = ap.parse_args()

    files = sorted(glob.glob(args.glob))
    runs = []
    for f in files:
        with open(f, encoding="utf-8") as fh:
            d = json.load(fh)
        if d.get("subset"):
            print(f"skip subset run: {f}")
            continue
        if int(d["n_users"]) != args.expect_users:
            print(f"skip {f}: n_users={d['n_users']} != {args.expect_users}")
            continue
        if int(d["test"]["n"]) != args.expect_users:
            print(f"skip {f}: test n={d['test']['n']}")
            continue
        runs.append((f, d))
    if not runs:
        raise SystemExit(f"no full runs matched {args.glob}")
    runs.sort(key=lambda x: int(x[1]["seed"]))

    seeds = [int(d["seed"]) for _, d in runs]
    if len(set(seeds)) != len(seeds):
        raise SystemExit(f"duplicate seeds: {seeds}")

    # per-seed rows
    rows = []
    for f, d in runs:
        cfg = d.get("config", {})
        row = {
            "row": f"seed={d['seed']}",
            "seed": d["seed"],
            "n_users": d["n_users"],
            "n_items": d["n_items"],
            "best_epoch": d["best_epoch"],
            "epochs_run": d.get("epochs_run", len(d.get("history", []))),
            **{f"test_{k}": d["test"][k] for k in METRICS},
            **{f"valid_{k}": d["valid"][k] for k in METRICS},
            "elapsed_sec": d["elapsed_sec"],
            "mean_epoch_sec": d.get("mean_epoch_sec"),
            "n_params": d["n_params"],
            "device": d["device"],
            "torch_threads": d.get("torch_threads", cfg.get("threads")),
            "lr": cfg.get("lr"),
            "patience": cfg.get("patience"),
            "max_epochs": cfg.get("epochs"),
            "batch_size": cfg.get("batch_size"),
            "source_json": str(Path(f).relative_to(ROOT)) if Path(f).is_relative_to(ROOT) else f,
        }
        rows.append(row)

    agg_mean = {"row": "mean", "seed": ",".join(map(str, seeds))}
    agg_std = {"row": "std(ddof=1)", "seed": ",".join(map(str, seeds))}
    for key in [f"test_{k}" for k in METRICS] + [f"valid_{k}" for k in METRICS] + [
        "best_epoch", "epochs_run", "elapsed_sec", "mean_epoch_sec",
    ]:
        vals = [float(r[key]) for r in rows if r[key] is not None]
        m, s = mean_std(vals)
        agg_mean[key], agg_std[key] = m, s
    agg_mean["n_params"] = rows[0]["n_params"]
    agg_mean["elapsed_sec_total"] = sum(float(r["elapsed_sec"]) for r in rows)

    fieldnames = list(rows[0].keys()) + ["elapsed_sec_total"]
    out_csv = Path(args.out_stem + ".csv")
    with open(out_csv, "w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=fieldnames)
        w.writeheader()
        for r in rows + [agg_mean, agg_std]:
            w.writerow({k: r.get(k, "") for k in fieldnames})

    # markdown
    d0 = runs[0][1]
    c0 = d0.get("config", {})
    n = len(rows)
    lines = []
    lines.append(f"# SASRec (CE, full softmax) — Amazon Beauty LOO, full data")
    lines.append("")
    lines.append(
        f"Auto-generated by `scripts/06_tables.py` from {n} run(s): "
        + ", ".join(f"`{r['source_json']}`" for r in rows)
        + ". Do not hand-edit."
    )
    lines.append("")
    lines.append(
        f"- Users {d0['n_users']}, full-catalog ranking over {d0['n_items']} items, history items **not** filtered; "
        f"valid uses train history, test uses train+valid history."
    )
    lines.append(
        f"- Device: {d0['device']} (CPU, no GPU; {platform.machine()}), torch threads per seed = "
        + ", ".join(f"s{r['seed']}:{r['torch_threads']}" for r in rows)
        + "; "
        f"seeds = {seeds} (n={n})."
    )
    lines.append(
        f"- Model: {c0.get('n_layers')} layers, {c0.get('n_heads')} heads, d={c0.get('hidden_size')}, "
        f"max_len={c0.get('max_seq_length')}, dropout={c0.get('hidden_dropout_prob')}/{c0.get('attn_dropout_prob')}, "
        f"lr={c0.get('lr')}, batch={c0.get('batch_size')}, max_epochs={c0.get('epochs')}, "
        f"early stop on valid NDCG@10 with patience={c0.get('patience')}. Params = {d0['n_params']:,}."
    )
    lines.append("- Mean ± sample std (ddof=1) across seeds.")
    lines.append("")
    lines.append("## Test (mean ± std)")
    lines.append("")
    lines.append("| Model | #seeds | " + " | ".join(k.upper().replace("HR", "HR").replace("NDCG", "NDCG") for k in METRICS) + " |")
    lines.append("|---|---|" + "---|" * len(METRICS))
    cells = [f"{agg_mean[f'test_{k}']:.4f} ± {agg_std[f'test_{k}']:.4f}" for k in METRICS]
    lines.append(f"| SASRec-CE | {n} | " + " | ".join(cells) + " |")
    lines.append("")
    lines.append("## Per seed")
    lines.append("")
    hdr = ["seed", "best_epoch", "epochs_run"] + [f"test {k.upper()}" for k in METRICS] + [
        "valid NDCG@10", "sec/epoch", "elapsed (min)", "#params"]
    lines.append("| " + " | ".join(hdr) + " |")
    lines.append("|" + "---|" * len(hdr))
    for r in rows:
        vals = [str(r["seed"]), str(r["best_epoch"]), str(r["epochs_run"])]
        vals += [f"{r[f'test_{k}']:.4f}" for k in METRICS]
        vals += [f"{r['valid_ndcg@10']:.4f}",
                 f"{r['mean_epoch_sec']:.1f}" if r["mean_epoch_sec"] is not None else "-",
                 f"{float(r['elapsed_sec']) / 60:.1f}", f"{r['n_params']:,}"]
        lines.append("| " + " | ".join(vals) + " |")
    lines.append("")
    lines.append(
        f"Total training wall time (sum over seeds; runs may overlap in parallel): "
        f"{agg_mean['elapsed_sec_total'] / 3600:.2f} h. Mean best_epoch = {agg_mean['best_epoch']:.1f} ± {agg_std['best_epoch']:.1f}."
    )
    lines.append("")
    out_md = Path(args.out_stem + ".md")
    out_md.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out_csv}\nwrote {out_md}")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
