#!/usr/bin/env python
"""Main table for all non-LLM baselines (+ paired significance tests), invoked by scripts/06_tables.py.

Reads configs/search/baselines.yaml, picks each method's configuration by seed-42 valid NDCG@10
(same rule as scripts/select_and_queue.py), aggregates results/<tag>_s{42..46}_metrics.json, and
runs paired tests on per-user test NDCG@10 from results/per_user/<tag>_s<seed>.npz.
Every number comes from files written by the training/evaluation scripts. Do not hand-edit outputs.
"""

from __future__ import annotations

import csv
import json
import math
import platform
from pathlib import Path

import numpy as np
import yaml
from scipy import stats

ROOT = Path(__file__).resolve().parents[1]
METRICS = ["hr@5", "hr@10", "hr@20", "ndcg@5", "ndcg@10", "ndcg@20"]
REFERENCE = "SASRec"


def ms(xs):
    xs = [float(x) for x in xs]
    m = sum(xs) / len(xs)
    s = math.sqrt(sum((x - m) ** 2 for x in xs) / (len(xs) - 1)) if len(xs) > 1 else 0.0
    return m, s


def ndcg10(ranks: np.ndarray) -> np.ndarray:
    r = ranks.astype(np.float64)
    return np.where(r <= 10, 1.0 / np.log2(r + 1.0), 0.0)


def holm(pvals: dict) -> dict:
    items = sorted(pvals.items(), key=lambda kv: kv[1])
    m, out, running = len(items), {}, 0.0
    for i, (k, p) in enumerate(items):
        running = max(running, min(1.0, (m - i) * p))
        out[k] = running
    return out


def main() -> None:
    cfg = yaml.safe_load(open(ROOT / "configs/search/baselines.yaml"))
    seeds = [int(s) for s in cfg["seeds"]]
    s0 = int(cfg["search_seed"])
    methods, search_rows = {}, []
    for name, m in cfg["methods"].items():
        cands = []
        for g in m["grid"]:
            p = ROOT / "results" / f"{g['tag']}_s{s0}_metrics.json"
            v = json.loads(p.read_text())["valid"]["ndcg@10"] if p.exists() else None
            cands.append((g, v))
            search_rows.append((name, g["label"], v))
        if any(v is None for _, v in cands):
            print(f"[table] {name}: search incomplete, skipped")
            continue
        g, _ = max(cands, key=lambda t: t[1])
        runs = []
        for sd in seeds:
            p = ROOT / "results" / f"{g['tag']}_s{sd}_metrics.json"
            if p.exists():
                d = json.loads(p.read_text())
                if d.get("subset") or int(d["test"]["n"]) != 22363:
                    continue
                pu = ROOT / "results" / "per_user" / f"{g['tag']}_s{sd}.npz"
                runs.append((sd, d, pu if pu.exists() else None))
        if runs:
            methods[name] = {"cfg": g, "runs": runs, "model": m["model"]}

    rows_csv, md = [], []
    md.append("# Main table — Amazon Beauty (RecBoard Amazon2014Beauty_550_LOU), non-LLM baselines")
    md.append("")
    md.append("Auto-generated by `scripts/06_tables.py` (→ `scripts/main_table.py`) from `results/<tag>_s<seed>_metrics.json` "
              "and `results/per_user/*.npz`. Do not hand-edit.")
    md.append("")
    md.append("- 22,363 users; full-catalogue ranking over 12,101 items with ONE shared evaluator (`pcdrec.evaluator`); "
              "history items **not** filtered; valid input = train history, test input = train + valid history.")
    md.append("- Same backbone capacity: d = 64, max_len = 50 (BERT4Rec: 49 history items + [MASK]); "
              "SASRec / SASRec-T / BERT4Rec 2 layers × 2 heads, FFN 256; GRU4Rec 1-layer GRU (hidden 64).")
    md.append("- Training: Adam lr 1e-3, batch 256 (MF-BPR 4096 pairs), early stopping on valid NDCG@10 (patience 20, "
              "≤200 epochs; MF-BPR ≤300). Tuning budget: 2 configurations per method on seed 42 "
              "(`configs/search/baselines.yaml`), selected by valid NDCG@10, then seeds 42–46.")
    md.append(f"- CPU only ({platform.machine()}, 8 cores, no GPU); mean ± sample std (ddof = 1) over seeds.")
    md.append("")
    md.append("## Test (mean ± std)")
    md.append("")
    md.append("| Method | selected config | #seeds | #params | " + " | ".join(k.upper() for k in METRICS) + " | train time / seed (min) |")
    md.append("|---|---|---|---|" + "---|" * len(METRICS) + "---|")
    order = sorted(methods, key=lambda n: -ms([d["test"]["ndcg@10"] for _, d, _ in methods[n]["runs"]])[0])
    for name in order:
        M = methods[name]
        cells = []
        for k in METRICS:
            mu, sd = ms([d["test"][k] for _, d, _ in M["runs"]])
            cells.append(f"{mu:.4f} ± {sd:.4f}")
        tmin = ms([d["elapsed_sec"] / 60 for _, d, _ in M["runs"]])
        n_params = M["runs"][0][1]["n_params"]
        md.append(f"| {name} | {M['cfg']['label']} | {len(M['runs'])} | {n_params:,} | " + " | ".join(cells) +
                  f" | {tmin[0]:.1f} ± {tmin[1]:.1f} |")
        for sd, d, pu in M["runs"]:
            rows_csv.append({"method": name, "config": M["cfg"]["label"], "tag": f"{M['cfg']['tag']}_s{sd}", "seed": sd,
                             **{f"test_{k}": d["test"][k] for k in METRICS},
                             **{f"valid_{k}": d["valid"][k] for k in METRICS},
                             "best_epoch": d["best_epoch"], "epochs_run": d.get("epochs_run"),
                             "elapsed_sec": d["elapsed_sec"], "n_params": d["n_params"],
                             "threads": d.get("torch_threads")})
    md.append("")

    # ---- paired significance tests vs SASRec on per-user test NDCG@10
    md.append("## Paired significance tests (test NDCG@10)")
    md.append("")
    tests = {}
    if REFERENCE in methods:
        ref = methods[REFERENCE]
        ref_pu = {sd: np.load(pu) for sd, _, pu in ref["runs"] if pu is not None}
        for name in order:
            if name == REFERENCE:
                continue
            M = methods[name]
            pu = {sd: np.load(p) for sd, _, p in M["runs"] if p is not None}
            common = sorted(set(pu) & set(ref_pu))
            if not common:
                continue
            a = np.mean([ndcg10(pu[s]["test_rank"]) for s in common], axis=0)
            b = np.mean([ndcg10(ref_pu[s]["test_rank"]) for s in common], axis=0)
            for s in common:
                assert np.array_equal(pu[s]["users"], ref_pu[s]["users"])
            diff = a - b
            w = stats.wilcoxon(a, b, zero_method="wilcox") if np.any(diff != 0) else None
            t = stats.ttest_rel(a, b)
            ma = [float(ndcg10(pu[s]["test_rank"]).mean()) for s in common]
            mb = [float(ndcg10(ref_pu[s]["test_rank"]).mean()) for s in common]
            ts = stats.ttest_rel(ma, mb) if len(common) > 1 else None
            tests[name] = {"seeds": common, "mean_diff": float(diff.mean()), "rel_diff_pct": float(100 * diff.mean() / b.mean()),
                           "wilcoxon_p": float(w.pvalue) if w else 1.0, "ttest_user_p": float(t.pvalue),
                           "ttest_seed_p": float(ts.pvalue) if ts is not None else None,
                           "n_users": int(len(a)), "users_better": int((diff > 0).sum()), "users_worse": int((diff < 0).sum())}
        hp = holm({k: v["wilcoxon_p"] for k, v in tests.items()})
        for k in tests:
            tests[k]["wilcoxon_p_holm"] = hp[k]
        md.append(f"Reference: **{REFERENCE}**. Per-user test NDCG@10 is first averaged over the common seeds, then "
                  "compared user-by-user (Wilcoxon signed-rank, two-sided; paired t-test as a check). Holm correction over "
                  f"the {len(tests)} comparisons. `seed-level t` = paired t-test on the per-seed means (n = #seeds).")
        md.append("")
        md.append("| Method vs SASRec | seeds | Δ NDCG@10 (abs) | Δ (%) | users better / worse | Wilcoxon p | Holm p | user-level t p | seed-level t p |")
        md.append("|---|---|---|---|---|---|---|---|---|")
        for name in order:
            if name not in tests:
                continue
            r = tests[name]
            md.append(f"| {name} | {len(r['seeds'])} | {r['mean_diff']:+.4f} | {r['rel_diff_pct']:+.1f}% | "
                      f"{r['users_better']} / {r['users_worse']} | {r['wilcoxon_p']:.2e} | {r['wilcoxon_p_holm']:.2e} | "
                      f"{r['ttest_user_p']:.2e} | {r['ttest_seed_p']:.2e} |" if r["ttest_seed_p"] is not None else
                      f"| {name} | {len(r['seeds'])} | {r['mean_diff']:+.4f} | {r['rel_diff_pct']:+.1f}% | "
                      f"{r['users_better']} / {r['users_worse']} | {r['wilcoxon_p']:.2e} | {r['wilcoxon_p_holm']:.2e} | "
                      f"{r['ttest_user_p']:.2e} | - |")
        strongest = next((n for n in order if n != REFERENCE), None)
        if strongest:
            md.append("")
            md.append(f"Strongest non-SASRec baseline by mean test NDCG@10: **{strongest}**.")
    md.append("")
    md.append("## Tuning (seed 42, valid NDCG@10)")
    md.append("")
    md.append("| Method | config | valid NDCG@10 |")
    md.append("|---|---|---|")
    for name, label, v in search_rows:
        md.append(f"| {name} | {label} | {v:.4f} |" if v is not None else f"| {name} | {label} | (not run yet) |")
    md.append("")
    md.append("## Per seed (test NDCG@10 / HR@10, best epoch, minutes)")
    md.append("")
    md.append("| Method | seed | test NDCG@10 | test HR@10 | valid NDCG@10 | best epoch | epochs run | minutes | threads |")
    md.append("|---|---|---|---|---|---|---|---|---|")
    for r in rows_csv:
        md.append(f"| {r['method']} | {r['seed']} | {r['test_ndcg@10']:.4f} | {r['test_hr@10']:.4f} | {r['valid_ndcg@10']:.4f} | "
                  f"{r['best_epoch']} | {r['epochs_run']} | {r['elapsed_sec'] / 60:.1f} | {r['threads']} |")
    md.append("")
    out = ROOT / "results" / "main_table_beauty"
    if rows_csv:
        with open(str(out) + ".csv", "w", newline="") as f:
            w = csv.DictWriter(f, fieldnames=list(rows_csv[0].keys()))
            w.writeheader()
            w.writerows(rows_csv)
    (ROOT / "results" / "main_table_beauty.md").write_text("\n".join(md), encoding="utf-8")
    (ROOT / "results" / "significance_beauty.json").write_text(json.dumps(tests, indent=2), encoding="utf-8")
    print("\n".join(md))


if __name__ == "__main__":
    main()
